DO_ODDANIA/django/pz/pz/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pz.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^qrpolls/', include('qrpolls.urls')),
    url(r'^qrpolls/', include('qrpolls.urls', namespace="qrpolls")),

    url(r'^admin/', include(admin.site.urls)),
)

DO_ODDANIA/django/pz/qrpolls/urls.py
'''
 Copyright 2014 Byliniak, Sliwka, Gambus, Celmer

 Licensed under the Surveys License, (the "License");
 you may not use this file except in compliance with the License.

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
'''

from django.conf.urls import patterns, url

from qrpolls import views

urlpatterns = patterns('',
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^create', views.create ,name='create'),
    url(r'^meeting/(?P<hash_id>\w+)/$', views.meeting, name='meeting'),
    url(r'^meetingCharts/(?P<hash_id>\w+)/$', views.meetingCharts, name='meetingCharts'),
    url(r'^meeting/(?P<hash_id>\w+)/newQuestion', views.newQuestion, name='newQuestion'),
    url(r'^meeting/(?P<hash_id>\w+)/api/(?P<question>\w+)/$$', views.api, name='api'),
    url(r'^meeting/(?P<hash_id>\w+)/api/vote/(?P<voter_id>\w+)/(?P<choice_ids>[A-Za-z0-9_,]+)/$$', views.api_vote_voter, name='api_vote_voter'),
)

DO_ODDANIA/django/pz/qrpolls/models.py
'''
 Copyright 2014 Byliniak, Sliwka, Gambus, Celmer

 Licensed under the Surveys License, (the "License");
 you may not use this file except in compliance with the License.

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
'''

from django.db import models

class QRPoll(models.Model):
    hash_id = models.CharField(max_length=200)  # id spotkania
    time = models.CharField(max_length=200)     # czas (data rozpoczenia/zakonczenia) spotkania
    room = models.CharField(max_length=200)     # mijesce
    subject = models.CharField(max_length=200)  # temat
    version = models.IntegerField(default=1)    # wersja spotkania (po dodaniu nowego pytania wersia++)

    def __str__(self):  # Python 3: def __str__(self):
        return self.hash_id

class Question(models.Model):
    poll = models.ForeignKey(QRPoll)                    # referencja do spotknia do ktorego przypisane jest pytanie
    question_text = models.CharField(max_length=200)    # tekst pytania
    question_choices_max = models.IntegerField(default=1) # maksymalna ilosc odpowiedzi do zaznaczenia na dane pytanie - 1 - odpowiedz jednokrotnego wyboru, 2 - max - wielokrotnego wyboru, 0 - pytanie otwarte
    isRating = models.BooleanField(default=False)       # true - pytaneie przetrzymuje informacje o ocenie spotkania
    def __str__(self):  # Python 3: def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question)              # referencja do pytania do ktorego przypisana jest ta odpowiedz
    choice_text = models.CharField(max_length=200)      # tekst odpowiedzi
    def __str__(self):  # Python 3: def __str__(self):
        return self.choice_text

class Vote(models.Model):
    choice = models.ForeignKey(Choice)                  # referencja do odpowiedzi do ktorej przypisany jest ten glos
    voter_id = models.CharField(max_length=200);        # id glosujacego
    extra = models.CharField(max_length=200);           # ekstra informacje (nie uzywany w normlanych odpowiedziach)
    def __str__(self):  # Python 3: def __str__(self):
        return self.voter_id

DO_ODDANIA/django/pz/qrpolls/forms.py
'''
 Copyright 2014 Byliniak, Sliwka, Gambus, Celmer

 Licensed under the Surveys License, (the "License");
 you may not use this file except in compliance with the License.

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
'''

from django import forms
from django.contrib.admin import widgets


class NewMeetingForm(forms.Form):
    time = forms.CharField(max_length=200,widget=forms.TextInput(attrs={'autocomplete':'off'}))
    room = forms.CharField(max_length=200)
    subject = forms.CharField(max_length=200)

DO_ODDANIA/django/pz/qrpolls/views.py
'''
 Copyright 2014 Byliniak, Sliwka, Gambus, Celmer

 Licensed under the Surveys License, (the "License");
 you may not use this file except in compliance with the License.

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
'''

from django.template import RequestContext, loader
from django.shortcuts import get_object_or_404, render, Http404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.core import serializers
import time

import hashlib
import json

from qrpolls.models import QRPoll, Question, Choice, Vote
from qrpolls.forms import NewMeetingForm


# Metoda wyswietlajaca strone glowna
def index(request):
    n = NewMeetingForm #formularz tworzacy nowe spotkanie
    return render(request, 'qrpolls/index.html',{'form': n})

# Metoda wyswietlajaca strone spotkania o id : hash_id
def meeting(request, hash_id):

    try:
        poll = QRPoll.objects.get(hash_id=hash_id) # pobieramy hash z bazy, jesli go nie ma w bazie bedzie 404
    except QRPoll.DoesNotExist:
        raise Http404

    question_list = Question.objects.filter(poll=poll)
    ratingQuestion = Question.objects.get(poll=poll, isRating=True) #pytanie o ocene spotkania (jest tylko jedno dlatego mozemy zrobic get)
    rating_list_choices = Choice.objects.filter(question=ratingQuestion) #lista odpowiedzi na pytanie ratingowe
    rating=0 #rating spotkania
    allVotersCount=0 #liczba wszystkich glosujacych
    for rate_choice in rating_list_choices: #dla kazdej odpowiedzi 0.0 ,0.5 ,1.5 ..
        voters = Vote.objects.filter(choice=rate_choice) #glosujacy na ta ocene
        votersCount=int(voters.count()) #liczba glosujacych na ta ocene
        allVotersCount+=votersCount
        rating+=float(rate_choice.choice_text)*votersCount

    if allVotersCount!=0: # gdyby nikt nie ocenil spotkania  
        rating/=allVotersCount

    rating = round(rating,2)

    # slownik {tekst_pytania : slownik {tekstOdpowiedzi : liczba glosow }}
    questionChoiceVotesDic={}


    for question in question_list:
        if question.isRating == True:
            continue
        choices_list = Choice.objects.filter(question=question)
        newDic = []
        newDic.append(["One", "Two"]); #wartosci maronetkowe, musza byc
        votesCounter=0
        for choice in choices_list:
            votesCounter+=Vote.objects.filter(choice=choice).count()
            newDic.append([choice.choice_text, choice.vote_set.count()])
        if votesCounter == 0: # jesli suma glosujacych jest rowna 0, wyswietl pusty wykres (na bialo)
            newDic.append(["No Votes", 1]);

    path = request.META['SERVER_NAME']+request.path
    data = {'poll': poll, 'url' : path, 'rating':rating, 'allVotersCount':allVotersCount, 'questionChoiceVotesDic':questionChoiceVotesDic};
    return render(request, 'qrpolls/meeting.html', data)

def meetingCharts(request, hash_id):
    try:
        poll = QRPoll.objects.get(hash_id=hash_id) # pobieramy hash z bazy, jesli go nie ma w bazie bedzie 404
    except QRPoll.DoesNotExist:
        raise Http404

    question_list = Question.objects.filter(poll=poll)
    ratingQuestion = Question.objects.get(poll=poll, isRating=True) #pytanie o ocene spotkania (jest tylko jedno dlatego mozemy zrobic get)
    rating_list_choices = Choice.objects.filter(question=ratingQuestion) #lista odpowiedzi na pytanie ratingowe
    rating=0 #rating spotkania
    allVotersCount=0 #liczba wszystkich glosujacych
    for rate_choice in rating_list_choices: #dla kazdej odpowiedzi 0.0 ,0.5 ,1.5 ..
        voters = Vote.objects.filter(choice=rate_choice) #glosujacy na ta ocene
        votersCount=int(voters.count()) #liczba glosujacych na ta ocene
        allVotersCount+=votersCount
        rating+=float(rate_choice.choice_text)*votersCount

    if allVotersCount!=0: # gdyby nikt nie ocenil spotkania 
        rating/=allVotersCount

    rating = round(rating,2)

    questionChoiceVotesDic={}

    # slownik {tekst_pytania : slownik {tekstOdpowiedzi : liczba glosow }}

    for question in question_list:
        if question.isRating == True:
            continue
        choices_list = Choice.objects.filter(question=question)
        newDic = []
        newDic.append(["One", "Two"]); #wartosci maronetkowe, musza byc
        votesCounter=0
        for choice in choices_list:
           # newDic[choice.choice_text] = choice.vote_set.count()
            votesCounter+=Vote.objects.filter(choice=choice).count()
            newDic.append([choice.choice_text, choice.vote_set.count()])
        if votesCounter == 0:
            newDic.append(["No Votes", 1]);

        print(votesCounter)
        questionChoiceVotesDic[question.question_text] =json.dumps(newDic)

    
    path = request.META['SERVER_NAME']+request.path

    data = {'poll': poll, 'url' : path, 'rating':rating, 'allVotersCount':allVotersCount, 'questionChoiceVotesDic':questionChoiceVotesDic};
    return render(request, 'qrpolls/meetingCharts.html', data)


# Metoda tworzaca nowe spotkanie
def create(request):
    m = hashlib.md5()

    subject = request.POST['subject']
    room = request.POST['room'] 
    timeMeeting = request.POST['time']


    millis = int(round(time.time() * 1000)) # czas ktory mamy teraz w miliseundach (sol do hasha)
    s = str(subject)+str(room)+str(timeMeeting)+str(millis)
    hash_id = hashlib.md5(s.encode()).hexdigest()

    poll = QRPoll(hash_id=hash_id, time = timeMeeting, room = room, subject = subject, version = 1);
    poll.save()

    # dla kazdego spotkania, nalezy stworzyc specjalne pytanie ratingowe
    question = Question(poll=poll, question_text = "Raiting", question_choices_max=1, isRating=True) # przykladowa ankieta
    question.save()

    choice = Choice(question=question, choice_text = "0")
    choice.save()
    choice = Choice(question=question, choice_text = "0.5")
    choice.save()
    choice = Choice(question=question, choice_text = "1.0")
    choice.save()
    choice = Choice(question=question, choice_text = "1.5")
    choice.save()
    choice = Choice(question=question, choice_text = "2.0")
    choice.save()
    choice = Choice(question=question, choice_text = "2.5")
    choice.save()
    choice = Choice(question=question, choice_text = "3.0")
    choice.save()
    choice = Choice(question=question, choice_text = "3.5")
    choice.save()
    choice = Choice(question=question, choice_text = "4.0")
    choice.save()
    choice = Choice(question=question, choice_text = "4.5")
    choice.save()
    choice = Choice(question=question, choice_text = "5.0")
    choice.save()


    return HttpResponseRedirect(reverse('qrpolls:meeting', args=(hash_id,)))

# Metoda dodajaca nowe pytanie do spotkania o id: hash_id
# Dane dotyczace nowego pytania zawarte sa w POST
def newQuestion(request,hash_id):
    questionText = request.POST['question']
    question_choices_max = request.POST['choicesMax']


    l = len(request.POST.keys()) # l - wielkosc slownika z post, powinny znajdowac się tam: dict_keys(['question', 'csrfmiddlewaretoken', 'choice0'])

    choices = []
    for currId in range(l-3): #poza polami wyboru w slowniku znajduja sie trzy inne pola (question, choicesMax, oraz csrfmiddlewaretoken), dlatego -3
        s = 'choice'+str(currId)
        choices.append(request.POST[s])

    try:
        poll = QRPoll.objects.get(hash_id=hash_id) # pobieramy hash z bazy, jesli go nie ma w bazie bedzie 404
    except QRPoll.DoesNotExist: 
        raise Http404

    poll.version+=1;
    poll.save()

    question = Question(poll=poll, question_text = questionText, question_choices_max= question_choices_max)
    question.save()

    for c in choices: 
        choice = Choice(question=question, choice_text = c)
        choice.save()

    return HttpResponseRedirect(reverse('qrpolls:meeting', args=(hash_id,)))


# Metoda odslugujaca zapytania do api.
# qrpolls/meeting/<hash_id>/api/info/ - zwraca informacje na temat spotkania
# qrpolls/meeting/<hash_id>/api/version/ - zwraca wersje spotkania
# qrpolls/meeting/<hash_id>/api/questions/ - zwraca pytania ktore sa przypisane do spotkania
# qrpolls/meeting/<hash_id>/api/choices/ - zwraca mozliwe odpowiedzi do tych pytan ktore sa przypisane do spotkania.
def api(request, hash_id, question):
    try:
        poll = QRPoll.objects.get(hash_id=hash_id) # pobieramy hash z bazy, jesli go nie ma w bazie bedzie 404
    except QRPoll.DoesNotExist: 
        raise Http404

    if question == "info":  #informacja o spotkaniu
        data = [ {'info': {
                'hash_id' : poll.hash_id,
                'time' : poll.time,
                'room' : poll.room,
                'subject' : poll.subject,
        }}]
        data_string = json.dumps(data)
        return HttpResponse(data_string)



    elif question == "version": #wersja spotkania, po dodaniu ankiety version++
        data = [ {'version': poll.version}]
        data_string = json.dumps(data)
        return HttpResponse(data_string)

   
    elif question == "questions": #pytania w tym spotkaniu
        data = serializers.serialize("json", Question.objects.filter(poll=poll))
        return HttpResponse(data)

    elif question == "choices": #odpowiedzi na pytania z tego spotkania
        question_list = Question.objects.filter(poll=poll)
        all_objects = []
        for question in question_list:

            all_objects.extend(list(Choice.objects.filter(question=question)))


        data = serializers.serialize('json', all_objects)

        return HttpResponse(data)


    raise Http404



    return HttpResponseRedirect(reverse('qrpolls:meeting', args=(hash_id,)))

# Metoda obslugujaca glosowanie z rozroznieniem glosujacych
# Tak po prawdzie do glosowanie nie jest potrzebny hash_id, ale przydaje aby po zaglosowaniu wyswietlic strone spotkania 

DO_ODDANIA/django/pz/qrpolls/templates/qrpolls/index.html
<!--
 Copyright 2014 Byliniak, Sliwka, Gambus, Celmer

 Licensed under the Surveys License, (the "License");
 you may not use this file except in compliance with the License.

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-->

<!DOCTYPE html>
  <!---->
  <head>
    <meta charset="UTF-8">
    <title>Surveys</title>

{% load staticfiles %}
<link rel="stylesheet" href="{% static 'qrpolls/style.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'qrpolls/timepicker/include/ui-1.10.0/ui-lightness/jquery-ui-1.10.0.custom.min.css' %}" type="text/css" />

<script type="text/javascript" src="{% static 'qrpolls/jquery-1.11.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'qrpolls/timepicker/include/ui-1.10.0/jquery.ui.core.min.js' %}" ></script>
<script type="text/javascript" src="{% static 'qrpolls/timepicker/include/ui-1.10.0/jquery.ui.widget.min.js' %}" ></script>
<script type="text/javascript" src="{% static 'qrpolls/timepicker/include/ui-1.10.0/jquery.ui.tabs.min.js' %}" ></script>
<script type="text/javascript" src="{% static 'qrpolls/timepicker/include/ui-1.10.0/jquery.ui.position.min.js' %}" ></script>
<script type="text/javascript" src="{% static 'qrpolls/timepicker/jquery.ui.timepicker.js' %}" ></script>

</head>
<body>

<div align="center" class="main">
    <header><img src="{% static 'qrpolls/img/logo.png' %}" alt="Logo"/></header>

<div id="123">
    <form action="create" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
    </form>
</div>

<style>
div.ui-datepicker{
 font-size:5px;
}

</style>


<script type="text/javascript">
     $('#id_time').timepicker({
    minutes: {
        interval: 5,
        manual: [ 0, 1, 30, 59 ]
    },
    showNowButton: true,
    showDeselectButton: true,
    defaultTime: '',  // removes the highlighted time for when the input is empty.
    showCloseButton: true

});

</script>
</body>

DO_ODDANIA/django/pz/qrpolls/templates/qrpolls/meeting.html
<!--
 Copyright 2014 Byliniak, Sliwka, Gambus, Celmer

 Licensed under the Surveys License, (the "License");
 you may not use this file except in compliance with the License.

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-->

<!DOCTYPE html>
 <!---->
<head>
<meta charset="UTF-8">
<title>Surveys</title>
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'qrpolls/style.css' %}" type="text/css" />
<script type="text/javascript" src="{% static 'qrpolls/newQuestion-scripts.js' %}" ></script>
<script type="text/javascript" src="{% static 'qrpolls/jquery-1.11.1.min.js' %}" ></script>
<script type="text/javascript" src="{% static 'qrpolls/raty-2.5.2/jquery.raty.min.js' %}" ></script>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript" src="{% static 'qrpolls/charts-scripts.js' %}" ></script>
<script type="text/javascript">
$.fn.raty.defaults.path = '{{ STATIC_URL }}qrpolls/raty-2.5.2/img';
</script>
<script type="text/javascript">
function refresh() {
var currUrl = document.URL;newUrl
var newUrl = currUrl.replace("meeting", "meetingCharts"); //zamina adresu url strony z meeting na meetingTest (po to aby django zlapal inny view)
$.ajax({
url: newUrl,
success: function(data) {
$('#charts').html(data);
}
});
setTimeout("refresh()", 5000);	//uruchom refresh() za 5 sec
}
$(function(){
refresh();
});
</script>
</head>
<body>
{% csrf_token %}
{% load qr_tags %}

<div align="center" class="main">
<header><img src="{% static 'qrpolls/img/logo.png' %}" alt="Logo"/></header>
<div class= "title">Subject: {{poll.subject}}</div>
<div class= "titleDetails">Room: {{poll.room}}</div>
<div class= "titleDetails">Time: {{poll.time}}</div>
<div align="center" id="qrCode">{% qr_from_text url "l" %}</div>

<div class="newQuestion">
<button id = "buttonCreateForm" onclick="createForm()">New Question</button>
</div>
<input id="csrf_token" type = "hidden" value="{{ csrf_token }}"/> <!-- token potrzebny aby przeslac POST do django - musi byc, nie ma rady -->
<div id = "newQuestionButtons"></div> <!-- miejsce w ktorym pojawia sie przyciski panelu tworzenia nowego pytania -->
<div id = "newQuestionDiv"> </div> <!-- miejsce na inne rzeczy (tresc pytania itp) -->

<div id = "charts">
{% include "meetingCharts.html" %}
</div>
</body>

DO_ODDANIA/django/pz/qrpolls/templates/qrpolls/meetingCharts.html
<!--
 Copyright 2014 Byliniak, Sliwka, Gambus, Celmer

 Licensed under the Surveys License, (the "License");
 you may not use this file except in compliance with the License.

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-->

<div id="rating" class="stars"> </div>


<script type="text/javascript">
$('#rating').raty(
	{	score: {{rating}},
		number : 5,
		readOnly : true,
		half: true,
		size   : 100,
		starHalf   : 'gwiazdka2.png',
		starOff    : 'gwiazdka3.png',
		starOn     : 'gwiazdka1.png' 
	});

</script>


{% with i=1  %}
{% for question, dict in questionChoiceVotesDic.items %}
<hr/>
<div id="chart_div{{forloop.counter}}" style="width: 700px; height: 400px;"> 
	<script type="text/javascript"> drawChart2("chart_div{{forloop.counter}}" ,"{{ question }}", "{{ dict }}");</script>
</div>
<!-- usuniecie problemu dziwnej "2"  -->
<div id = "xD" style="display: none;">
{{ i|add:1 }}
</div>
{% endfor %}
{% endwith %}  